import importlib

PACKAGES = [
    "noveland.adapters",
    "noveland.adapters.model_provider",
    "noveland.adapters.models",
    "noveland.agents",
    "noveland.agents.contracts",
    "noveland.agents.models",
    "noveland.agents.services",
    "noveland.auth",
    "noveland.auth.contracts",
    "noveland.auth.errors",
    "noveland.auth.models",
    "noveland.auth.seed_admin",
    "noveland.auth.services",
    "noveland.calendar",
    "noveland.calendar.contracts",
    "noveland.calendar.models",
    "noveland.calendar.services",
    "noveland.conversations",
    "noveland.conversations.contracts",
    "noveland.conversations.errors",
    "noveland.conversations.models",
    "noveland.conversations.services",
    "noveland.core",
    "noveland.core.models",
    "noveland.events",
    "noveland.events.contracts",
    "noveland.events.errors",
    "noveland.events.event_store",
    "noveland.events.models",
    "noveland.events.publisher",
    "noveland.events.replay",
    "noveland.memory",
    "noveland.memory.backends",
    "noveland.memory.contracts",
    "noveland.memory.evals",
    "noveland.memory.local_pgvector",
    "noveland.memory.models",
    "noveland.memory.vector_type",
    "noveland.media",
    "noveland.media.catalog",
    "noveland.media.contracts",
    "noveland.media.errors",
    "noveland.media.models",
    "noveland.media.service",
    "noveland.media.storage",
    "noveland.narrative",
    "noveland.narrative.contracts",
    "noveland.narrative.models",
    "noveland.narrative.services",
    "noveland.observability",
    "noveland.observability.contracts",
    "noveland.observability.models",
    "noveland.observability.services",
    "noveland.plugins",
    "noveland.plugins.categories",
    "noveland.plugins.definition",
    "noveland.plugins.errors",
    "noveland.plugins.manifest",
    "noveland.plugins.registry",
    "noveland.services.api",
    "noveland.services.api.authorization",
    "noveland.services.api.auth",
    "noveland.services.api.conversations",
    "noveland.services.api.csrf",
    "noveland.services.api.dependencies",
    "noveland.services.api.media",
    "noveland.services.api.runtime",
    "noveland.services.api.worlds",
    "noveland.services.runtime",
    "noveland.services.runtime.agent_loop",
    "noveland.services.runtime.clock_tick",
    "noveland.services.runtime.conversation_loop",
    "noveland.services.runtime.daemon",
    "noveland.storage",
    "noveland.worlds",
    "noveland.worlds.clock",
    "noveland.worlds.clock_service",
    "noveland.worlds.models",
]


def test_workspace_packages_are_importable() -> None:
    for package_name in PACKAGES:
        assert importlib.import_module(package_name)
